.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified 1993-07-24 by Rik Faith (faith@cs.unc.edu)
.\" Modified 2002-08-10 by Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\"*******************************************************************
.\"
.\" This file was generated with po4a. Translate the source file.
.\"
.\"*******************************************************************
.TH COPYSIGN 3 "25 mars 2012" GNU "Manuel du programmeur Linux"
.SH NOM
copysign \- Copier le signe d'un nombre
.SH SYNOPSIS
.nf
\fB#include <math.h>\fP
.sp
\fBdouble copysign(double \fP\fIx\fP\fB, double \fP\fIy\fP\fB);\fP
.br
\fBfloat copysignf(float \fP\fIx\fP\fB, float \fP\fIy\fP\fB);\fP
.br
\fBlong double copysignl(long double \fP\fIx\fP\fB, long double \fP\fIy\fP\fB);\fP
.fi
.sp
Effectuez l'édition des liens avec l'option \fI\-lm\fP.
.sp
.in -4n
Exigences de macros de test de fonctionnalités pour la glibc (consultez
\fBfeature_test_macros\fP(7))\ :
.in
.sp
.ad l
\fBcopysign\fP(), \fBcopysignf\fP(), \fBcopysignl\fP()\ :
.RS 4
_SVID_SOURCE || _BSD_SOURCE || _XOPEN_SOURCE\ >=\ 600 || _ISOC99_SOURCE
|| _POSIX_C_SOURCE\ >=\ 200112L
.br
ou \fIcc\ \-std=c99\fP
.RE
.ad b
.SH DESCRIPTION
La fonction \fBcopysign\fP() renvoie un nombre dont la valeur absolue est celle
de \fIx\fP, mais dont le signe est celui de \fIy\fP.

Par exemple, \fIcopysign(42.0,\ \-1.0)\fP et \fIcopysign(\-42.0, \-1.0)\fP renvoient
toutes les deux \-42.0.
.SH "VALEUR RENVOYÉE"
En cas de succès, ces functions renvoient la valeur absolue de \fIx\fP, et le
signe de \fIy\fP.

Si \fIx\fP est NaN («\ Not a Number\ »), la fonction renvoie NaN avec le signe
de \fIy\fP.
.SH ERREURS
Aucune erreur ne se produit.
.SH CONFORMITÉ
.\" 4.3BSD.
C99, POSIX.1\-2001. Cette fonction est définie dans IEC 559 (et l'annexe avec
les fonctions recommandées de IEEE 754/IEEE 854).
.SH NOTES
Sur des architectures où le format des nombres flottants n'est pas conforme
à IEEE\ 754, la fonction \fBcopysign\fP() peut traiter un zéro négatif comme
positif.
.SH "VOIR AUSSI"
\fBsignbit\fP(3)
.SH COLOPHON
Cette page fait partie de la publication 3.52 du projet \fIman\-pages\fP
Linux. Une description du projet et des instructions pour signaler des
anomalies peuvent être trouvées à l'adresse
\%http://www.kernel.org/doc/man\-pages/.
.SH TRADUCTION
Depuis 2010, cette traduction est maintenue à l'aide de l'outil
po4a <http://po4a.alioth.debian.org/> par l'équipe de
traduction francophone au sein du projet perkamon
<http://perkamon.alioth.debian.org/>.
.PP
Christophe Blaess <http://www.blaess.fr/christophe/> (1996-2003),
Alain Portal <http://manpagesfr.free.fr/> (2003-2006).
Florentin Duneau et l'équipe francophone de traduction de Debian\ (2006-2009).
.PP
Veuillez signaler toute erreur de traduction en écrivant à
<perkamon\-fr@traduc.org>.
.PP
Vous pouvez toujours avoir accès à la version anglaise de ce document en
utilisant la commande
«\ \fBLC_ALL=C\ man\fR \fI<section>\fR\ \fI<page_de_man>\fR\ ».
